# StaffCommunication2 By FishbirdDD

# ========= PLEASE READ ========= #
# If you are unsure of the purpose of any part of this config, you can go to the spigot 
# page and find the link to my wiki.
# If you are sill unsure, you can join my support discord here: discord.gg/e2Hdh97
# (link on spigot page if that doesn't work)
# =============================== #

# Modify all of the messages in the plugin
messages:
  chats:
    staff: "&8[&bStaffChat&8] &d%player%: &b%message%"
    admin: "&8[&cAdminChat&8] &d%player%: &c%message%"
  broadcasts:
    server: "&6Broadcast > %message%"
    staff: "&bStaff Broadcast > %message%"
    admin: "&cAdmin Broadcast > %message%"
  staffmessage:
    receiver: "&a[Admin > You] %message%"
    sender: "&aMessage &7%message% &asent successfully"
  errors:
    permission: "&cYou do not have permission to use this command"
    usage: "&cUsage: %usage%"
    player: "&cThat player is not online"
  toggles:
    staff:
      enable: "&aEnabled staff chat"
      disable: "&cDisabled staff chat"
    admin:
      enable: "&aEnabled admin chat"
      disable: "&cDisabled admin chat"
  reload: "&aStaffCommunication %version% > configuration reloaded"
  version: "&aStaffCommunication %version% By FishbirdDD"

settings:
  # Output debug messages in console 
  debug: false
  # Should /ac or /sc with no message behave the same
  # as /sctoggle or /actoggle
  toggle-with-no-message: false

# === DO NOT EDIT ANYTHING BELOW THIS LINE === #

do-not-edit:
  config-version: 1
